version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - export AWS_ACCOUNT_ID=`echo $CODEBUILD_BUILD_ARN | awk -F":" '{print $5}'`
      - cd chat-bot/lex-model
      - chmod +x gen-lex-model.sh
      - npm install -g npm@latest
      - npm ci
  build:
    commands:
      - ./gen-lex-model.sh
